config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :projects, only: %i[index show update] do
    resources :comments, only: %i[show create]
  end

  # Defines the root path route ("/")
  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  has_many :comments, class_name: 'Comment', foreign_key: 'parent_id'
  belongs_to :parent, class_name: 'Comment', optional: true
  belongs_to :project
  belongs_to :user
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :comments, -> { where(parent_id: nil) }
  # has_many :direct_comments, -> { where(parent_id: nil) }, class_name: 'Comment'

  enum :status, %i[draft pending verified rejected]

  validates :status, inclusion: { in: statuses.keys }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
  has_many :comments
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# App Controller
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_back

  def redirect_back(error)
    flash.alert = error.message

    redirect_to root_path
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# Controller class for Comments
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :read_current_comment, only: %i[show]

  def show; end

  def create
    Comment.create(comment: params[:comment], project_id: params[:project_id], user_id: current_user.id)

    redirect_to project_path(id: params[:project_id])
  end

  private

  def read_current_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# Controller for projects
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :read_current_project, only: %i[show update]

  def index
    @projects = Project.all
  end

  def show; end

  def update
    @project.update(status: params[:status])
  rescue StandardError => e
    flash.alert = e.message
  ensure
    redirect_to project_path(@project)
  end

  private

  def read_current_project
    @project = Project.includes(:comments).find(params[:id])
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# Sessions controller
class SessionsController < Devise::SessionsController
  before_action :authorize_access_request!, only: :destroy
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectConversationHistory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_comment.html.erb
<div class="row">
  <div class="form-floating mt-2 mb-2">
    <textarea id="text-<%=comment.id%>" class="form-control" placeholder="Leave a comment here" style="height: 100%;" disabled>
      <%= comment.comment %>
    </textarea>
    <label for="text-<%=comment.id%>">@<%= comment.user.username %></label>
  </div>
  <!--
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <button type="button" class="btn btn-link">Edit</button>
    <button type="button" class="btn btn-link">Save</button>
    </div>
  -->
</div>
<% if comment.comments %>
  <div class="container">
    <div class="row">
      <div class="float-end">
        <!-- render partial: 'comment', collection: comment.comments -->
      </div>
      <br>
    </div>
  </div>
<% end %>

app/views/projects/index.html.erb
<h2 class="mb-4">
  Projects
  <small class="text-muted">List of all projects</small>
</h2>

<% flash.each do |type, msg| %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<ol class="list-group list-group-numbered mt-4">
  <% @projects.each do |project| %>
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <div class="fw-bold">
          <%= link_to project.name, project %>
        </div>
        <%= project.description %>
      </div>
      <span class="badge bg-primary rounded-pill"><%= project.comments.count %></span>
    </li>
  <% end %>
</ol>

app/views/projects/show.html.erb
<h2>
  Project:
  <small class="text-muted"><%= @project.name %></small>
</h2>

<% flash.each do |type, msg| %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<dl class="row">
  <dt class="col-sm-3">Status</dt>
  <dd class="col-sm-9">
    <%= form_for(@project) do |f| %>
      <select onchange="this.form.submit()" class="form-select" aria-label="Default select example" name="status">
        <%= Project.statuses.keys.each do |status| %>
          <option <%= @project.status == status ? 'selected' : '' %> value="<%= status %>">
          <%= status.titleize %>
          </option>
        <% end %>
        <option value="fake">fake</option>
      </select>
    <% end %>
  </dd>
</dl>

<%= link_to "← Projects", projects_path, class: 'btn btn-outline-secondary mt-4 mb-4' %>

<%= render partial: 'comment', collection: @project.direct_comments %>
<%= form_for('New Comment', url: project_comments_path(project_id: @project.id)) do |f| %>
  <div class="form-floating mt-2 mb-2">
    <textarea class="form-control" placeholder="Leave a comment here" name="comment" style="height: 100%;"></textarea>
    <label for="floatingTextarea">Comment</label>
  </div>

  <%= f.submit :Comment, class: 'btn btn-success' %>
<% end %>